version: "3"

services:
  pulumi-service:
    platform: linux/amd64
    image: pulumi/pulumi-python:latest
    working_dir: /pulumi/projects
    environment:
      PULUMI_HOME: /pulumi/projects/.cache
      PULUMI_CONFIG_PASSPHRASE: ""
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    volumes:
      - "${APP_ROOT}:/pulumi/projects"
